config/routes.rb
App::Application.routes.draw do

  get "page/emaildon", :to => "page#emaildon"

  get "page/home", :to => "page#home"
  get "page/ember", :to => "page#ember"
  get "/landing", :to => "page#landing"
  get "page/saved", :to => "page#saved"
  get "/terms_of_service", :to => 'page#terms_of_service'
  get "/buttons", :to => 'page#buttons'
  get "/privacy", :to => 'page#privacy'
  get "/contact", :to => 'page#contact'
  get "/about", :to => 'page#about'

  get "modal/report_tag", :to => "page#report_tag"
  get "modal/report_item", :to => "page#report_item"
  get "modal/relift", :to => "page#relift"
  get "modal/share", :to => "page#share"

  get 'hashtagbrands/search', :to => 'hashtagbrands#search'
  get 'hashtagbrands/:id/related', :to => 'hashtagbrands#related'
  resources :hashtagbrands

  #resources :images TODO delete this and any other image artifacts
  resources :posts
  resources :categories, :only => [:index, :edit, :update]
  post "categories/:id/update", :to => "categories#update"
  get "post/create", :to => "posts#create"
  post "posts/:id/update", :to => "posts#update"

  root :to => "page#ember"

  #
  # Users
  #
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" } #, :skip => [:registrations,:passwords,:unlocks]
  # makes domain/login work as well as domain/users/login
  devise_scope :user do
    get "login"  => "devise/sessions#new"
    get "logout" => "devise/sessions#destroy"
    #delete "logout" => "devise/sessions#destroy"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    collection do
      get :whoami
      post :avatar
      post :validate_username
      get :validate_email
    end

    resources :followers, :only => [:index]
    resources :following, :only => [:index]
  end

  get "users/following/:id", :to => "users#following"

  get "users/username/:username", :to => "users#show", :identifier => "username"
  # Browser / system compatability
  post "users/:id/edit", :to => "users#update"
  post "users/:id/delete", :to => "users#destroy"

  #
  # Timelines
  #
  get "unseen", :to => "timelines#unseen" # test method for console, delete if you'd like
  get "timelines", :to => "timelines#index"
  get "timelines/users/:id", :to => "timelines#show_user"
  get "timelines/recent", :to => "timelines#show_recent"
  get "timelines/hashtags/:name", :to => "timelines#show_hashtags"

  #
  # Parser and Bookmarklet
  #
  get 'bookmarklet/iframe', :to => 'parser#iframe',      :as => :bookmarklet_iframe
  get 'bookmarklet',        :to => 'parser#bookmarklet', :as => :bookmarklet

  post "parse", :to => "parser#parse"
  get "dynascript", :to => "parser#dynascript"
  get "brandscript", :to => "parser#brandscript"


  #
  # Items
  #
  resources :items do
    member do
      get :image, :visit
      post :relift
    end
    get :search, :on => :collection
    resources :hashtags, :only => [:create]
  end
  # # Browser / system compatability
  post "items/:id/edit", :to => "items#update"
  post "items/:id/delete", :to => "items#destroy"

  get "createItem", :to => "items#create"
  get "history/:id", :to => "items#history"
  post "items/:id/email", :to => "items#email"

  #
  # Hashtags
  #
  get "hashtags/popular", :to => "hashtags#show_popular"
  get "hashtags/search", :to => "hashtags#search"
  delete "hashtags/:id" => "hashtags#destroy"
  post "hashtags/create", :to => "hashtags#create"
  # Browser / system compatability
  post "hashtags/:id/delete" => "hashtags#destroy"

  #
  # Subscriptions
  #
  get "subscriptions", :to => "subscriptions#index"
  get "subscriptions/users/:id", :to => "subscriptions#show"
  post "subscriptions", :to => "subscriptions#create"
  delete "subscriptions/:id", :to => "subscriptions#destroy"
  # Browser / system compatability
  post "subscriptions/users/:id/delete", :to => "subscriptions#destroy"

  #
  # Suggestions
  #
  get "suggestions", :to => "suggestions#index"

  #
  # Set Asides
  #
  get "set_asides", :to => "set_asides#index"
  post "set_asides", :to => "set_asides#create"
  delete "set_asides/items/:id", :to => "set_asides#destroy"
  # Browser / system compatability
  post "set_asides/items/:id/delete", :to => "set_asides#destroy"

  #
  # Flags
  #
  get "flags", :to => "flags#index"
  post "flags/items/:id", :to => "flags#create_item"
  post "flags/hashtags/:id", :to => "flags#create_hashtag"

  #
  # Statistics
  #
  get "statistics/users/:id", :to => "statistics#show_user"
  get "statistics/items/:id", :to => "statistics#show_item"

  #
  #Error Handling
  #
  match "/", :to => "application#render_error", :status => 404
  match "*path", :to => "application#render_error", :status => 404

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :post, :conditions => ["posts.status = 1"]
  has_one :user, :through => :post, :conditions => ["users.status = 1"]
  belongs_to :user, :conditions => ["users.status = 1"]
  has_many :hashtags, :through => :post, :conditions => ["hashtags.status = 1"]
  has_many :hashtag_values, :through => :hashtags
  has_many :hashtagbrands_hashtags, :through => :hashtag_values, :source => :hashtagbrand
  has_many :suggestions
  has_many :set_asides
  has_many :subscriptions, :foreign_key => :user_id, :primary_key => :user_id, :conditions => ["subscriptions.status = 1"]
  has_many :user_item_views, :through => :subscriptions, :foreign_key => 'subscriptions.follower_id', :primary_key => 'subscriptions.user_id'
  belongs_to :parent, :class_name => "Item", :foreign_key => "parent_id", :conditions => ["items.status = 1"]

  validates :user_id, :post_id, :presence => true
  validates :post_id, :uniqueness => {:scope => [:user_id]}

  scope :saved_by, lambda{ |user| joins(:set_asides).where('set_asides.user_id = ?', user.id) }

  def self.between(params)
    return scoped unless params[:above].present? && params[:below].present?
    where("#{table_name}.id BETWEEN #{params[:above]} AND #{params[:below]}")
  end

  def retailer
    post.retailer
  end

  def name
    post.name
  end

  def price
    post.price
  end

  def photo
    post.photo
  end

  def items
    post.items
  end

  def <=> other
    self.created_at <=> other.created_at
  end

  def saved_by?(user)
    return false if user == nil
    aside_by(user).present?
  end

  def aside_by(user)
    return false if user == nil
    set_asides.where(:user_id => user.id).first
  end
end

app/views/items/_item.html.erb
<div class="<%= item.saved_by?(current_user) ? 'saved' : '' %> productBox" id="item_<%= item.id %>">
  <div class="productBox1">
    <div class="profileImgPan"></div>
    <div class="circle-overflow">
      <%= image_tag(item.user.avatar.url(:small), height: '116px', width: '87px') %>
    </div><!--/circle-overflow-->
    <h2 class="full_name"><%= item.user.full_name %></h2>
    <% if item.comment && item.comment.strip != '' %>
      <blockquote>
        <%= image_tag('begining-qoute.png', class: 'left') %>
        <p class="item_comment"><%= item.comment %></p>
        <%= image_tag('end-qoute.png') %>
      </blockquote>
    <% end %>
    <div class="productImg">
        <%= image_tag(item.photo.url(:small), width: '353px', height: '410px')  %>
    </div>
    <div class="productPricePan">
      <p class="productName"><%= min_name(item.post.brand.name, 20) %></p>
      <p class="productPrice">
        <span class="name"><%= min_name(item.post.name, 22) %></span>
        <span class="price"><%= number_to_currency(item.price, :precision => 0) %></span></p>
        <a href="#" class="liftBtn modal" 
          rel="#tsl-relift-popup"
          data-modalType="relift"
          data-modal-rails="relift?post_id=<%= item.id%>"
          data-modal-selector="#tsl-relift-popup">
        </a>
    </div>  
  </div>
  <a href="#" id="slideBtn<%=item.id%>" class="slideBtn">Slide</a>
  
  <div class="productBox2">
     <ul class="tabNav">
       <li class="tab1" rel="tabContent1"><a href="#">Tags</a></li>
       <li class="tab2" rel="tabContent2"><a href="#">History</a></li>
       <div class="clear"></div>
     </ul>
     
     <div class="tabContent tabContent1">
       <div class="tabLinkPan">
         <div class="tabInnerLink tag-txt"><a href="#">Enter tag here</a></div>
         <% item.hashtags.each do |tag| %>
           <div class="tabInnerLink"><a href="#"><%= tag.hashtag_value.value %></a></div>
         <% end %>
       </div>
       <div class="bottomButtonPan">
         <a href="#" class="shareBtn modal"
              rel="#tsl-share-popup"
              data-modalType="share"
              data-modal-rails="share?post_id=<%= item.id%>"
              data-modal-selector="#tsl-share-popup"
           >
           SHARE
         </a>
         <a href="#" class="btnSetAside saveBtn <%= item.saved_by?(current_user) ? 'has_aside' : '' %>" 
            item_id="<%= item.id %>" 
            set_aside_id="<%= item.aside_by(current_user).id if item.saved_by?(current_user) %>" >
               <%= item.saved_by?(current_user) ? 'SAVED' : 'SAVE' %>
         </a>
         <a href="<%= item.post.url %>" class="buyBtn" target="_blank">BUY</a>
       </div>
       <div class="bottomButtonPan-shadow"></div>
     </div>
     <div class="tabContent tabContent2">
       <div class="tabLinkPan">
         <% item.items.sort.slice(1..-1).each do |i| %>
           <% next unless i.user.present? && i != 1 %>
             <div class="tabInnerLink"><%= link_to user_image_and_value(i.user, i.user.full_name), '#' %></div>
         <% end %>
         <div class="tabInnerLink tag-txt"><a href="#">First Lifted By</a></div>
         <div class="tabInnerLink"><%= link_to user_image_and_value(item.items.first.user, item.items.first.user.full_name), '#' %></div>
       </div>
     </div>
  </div>
</div>
<script>
  /* needs to be here so it runs when pulled via AJAX */

  $('.full_name').quickfit({ max: 42, min: 12, truncate: false });
  $('.item_comment').quickfit({ max: 24, min: 12, width: 630, truncate: true });

</script>

app/views/items/_item_save.html.erb
<!-- my thought was to save this until the new design is done but delete if it bothers you -->
<div class="entry <%= item.saved_by?(current_user) ? 'saved' : '' %> productBox" id="item_<%= item.id %>"> <div class="entryHead">
    <%= link_to image_tag(item.user.avatar.url(:thumb)), item.user %>
    <p class="user">
      <%= link_to item.user.full_name, item.user %>
      <br/><span class="location"><%= item.user.hometown %></span>
    </p>
  </div>
  <div class="productMain">
    <div class="product">
      <div class="productDetails">
        <h2><%= item.retailer %><br/><span class="productDescription"><%= item.name %></span></h2>
        <div class="price"><%= number_to_currency(item.price, :precision => 0) %></div>
        <ul class="actions">
          <li>
          <a href="#" class="modal" data-modalType="relift" data-modal-rails="relift?post_id=<%= item.id%>">Re-lift</a></li>
          <li>
            <a href="#" class="btnSetAside <%= item.saved_by?(current_user) ? 'has_aside' : '' %>"
              item_id="<%= item.id %>"
              set_aside_id="<%= item.aside_by(current_user).id if item.saved_by?(current_user) %>"
            >
              <%= item.saved_by?(current_user) ? 'Un-Save' : 'Save' %>
            </a>
          </li>
          <li><a href="#" class="modal" data-modalType="share">Share</a></li>
          <li><a href="#">Buy</a></li>
        </ul>
      </div>
      <%= link_to image_tag(item.photo.url(:small)), image_item_path(item), :class => 'modal_link' %>
    </div>
    <div class="productMeta">
      <div class="comment">
        <p><%= item.comment %></p>
        <p>Lifted <%= time_ago_in_words(item.created_at) %> Ago</p>
      </div>
      <ul class="tabs">
        <li class="current"><a href="#tagWrap">Tags</a></li>
        <li style="float:right"><a href="#historyWrap">History</a></li>
      </ul>
      <div class="toggleWrap" id="tagWrap" style="display:block;">
        <div class="add-tag">
          <form action="hashtags" method="post" name="add_tag_form">
            <img src="../img/global/user-thumb-holder.gif" alt="user-thumb-holder" width="25" height="25" class="user-tiny-thumb"/>
            <input type="text" class="text" name="hashtag_value" value="Add a Tag" style="width: 115px;" />
            <input type="hidden" name="item_id" value="<%= item.id%>"/>
            <input type="submit" name="submit" class="addSubmit" style="float: right;"/>
          </form>
        </div>
        <div class="itemList">
          <div class="scrollWrap">
            <ul class="tagList" id="tagListForItemId<%= item.id %>">
              <% item.hashtags.each do |tag| %>
                <li><%= link_to user_image_and_value(tag.user, tag.hashtag_value.value), '#' %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="productTattle">
          <a href="#" class="modal flagItem" data-modalType="flagItem" data-modal-rails="report_item?post_id=<%= item.id%>">Flag Item</a>
          <a href="#" class="modal reportTag" data-modalType="reportTag" data-modal-rails="report_tag?post_id=<%= item.id%>">Report a Tag</a>
        </div>
      </div>
      <div class="toggleWrap" id="historyWrap" style="display:none;">
        <% if item.items.any? %>
          <p>Re-Lifted By:</p>
          <div class="itemList">
            <div class="scrollWrap">
              <ul>
                <% item.items.sort.each do |i| %>
                  <% next unless i.user.present? %>
                  <li><%= link_to user_image_and_value(i.user, i.user.full_name), '#' %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <p>First Lifted By:</p>
          <ul class="firstLifted">
            <li><%= link_to user_image_and_value(item.items.first.user, item.items.first.user.full_name), '#' %></li>
          </ul>
        <% else %>
          <p>No Re-lifts yet.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/_share.html.erb
<div class="tsl-share-popup-wrap" id="tsl-share-popup" style="display:none;">
	
    <div class="tsl-share-popup">

    	<div class="tsl-share-popup-header-wrap">
        	<div class="tsl-share-popup-icons-wrap">
                <a href="javascript:;" class="tsl-share-popup-twitter-icon"></a>
                <a href="javascript:;" class="tsl-share-popup-facebook-icon"></a>
                <a href="javascript:;" class="tsl-share-popup-pinterest-icon"></a>
                <a href="javascript:;" class="tsl-share-popup-email-icon"></a>
            </div><!--/tsl-share-popup-icons-wrap-->

<div class="clear"></div>
        </div><!--/tsl-share-popup-header-wrap-->

    		<a href="javascript:;" class="close"></a>

    	<div class="tsl-share-popup-scaffold">
        	<h4 class="share-above-image-txt">Email it:</h4>
        	<div class="tsl-share-popup-img-shadow"></div><!--/tsl-share-popup-img-wrap-->
            <div class="tsl-share-popup-img">
            	<div class="tsl-share-popup-img-text-box">

                  <div class="tsl-share-popup-brand-text">J. Crew</div>         
                  <div class="tsl-share-popup-item-text">Polka-Dot Popover</div>
                  <div class="tsl-share-popup-price-text">$35.00</div>     
<div class="clear"></div>  	
                </div><!--/tsl-share-popup-img-text-box-->
            </div><!--/tsl-share-popup-img-->

            <div class="tsl-share-popup-right-content">
            	<form class="tsl-share-popup-form" action="">

                    <div class="tsl-share-popup-second-screen-form">
                        <h4>To</h4>
                        <textarea class="tsl-share-popup-textarea-tags" name="tags"></textarea>

                        <h4>Subject</h4>
                        <input class="tsl-share-popup-subject-input" name="subject" value=""></textarea>

                        <h4>Thoughts (optional)</h4>
                        <textarea class="tsl-share-popup-input-thoughts" name="thoughts"></textarea>
                    </div><!--/tsl-share-popup-second-screen-form-->

                 <input type="submit" id="share-email-submit" alt="submit" name="submit" value="Send" />

                </form>

            </div><!--/tsl-share-popup-right-content-->
        </div><!--/tsl-share-popup-scaffold-->

    </div><!--/tsl-share-popup-->
    
</div><!--/tsl-share-popup-wrap-->

app/views/items/image.html.erb
<h2><%= @item.name %></h2>
<div class="modalContent">
  <%= image_tag @item.photo.url(:original) %>
</div>

app/views/items/show.html.erb
<% content_for :head do %>
  <%= tag :meta, property: "fb:app_id", content: ENV["FACEBOOK_APP_ID"] %>
  <%= tag :meta, property: "og:site_name", content: "theShoplift" %>
  <%= tag :meta, property: "og:type", content: "object" %>
  <%= tag :meta, property: "og:title", content: (@item.post.brand.name+':'+@item.post.name) %>
  <%= tag :meta, property: "og:description", content: ('Brand: '+@item.post.brand.name+', description: '+@item.post.name + ' ' + @item.post.description) %>
  <%= tag :meta, property: "og:url", content: item_url(@item) %>
  <%= tag :meta, property: "og:image", content: image_path(@item.photo) %>
<% end %>

<div id="content">
  <div class="centerCol">
    <%= render @item  %>
  </div>
  <div class="clear"></div>
</div>