config/routes.rb
App::Application.routes.draw do

  get "page/emaildon", :to => "page#emaildon"

  get "page/home", :to => "page#home"
  get "page/ember", :to => "page#ember"
  get "/landing", :to => "page#landing"
  get "page/saved", :to => "page#saved"
  get "/terms_of_service", :to => 'page#terms_of_service'
  get "/buttons", :to => 'page#buttons'
  get "/privacy", :to => 'page#privacy'
  get "/contact", :to => 'page#contact'
  get "/about", :to => 'page#about'

  get "modal/report_tag", :to => "page#report_tag"
  get "modal/report_item", :to => "page#report_item"
  get "modal/relift", :to => "page#relift"
  get "modal/share", :to => "page#share"

  get 'hashtagbrands/search', :to => 'hashtagbrands#search'
  get 'hashtagbrands/:id/related', :to => 'hashtagbrands#related'
  resources :hashtagbrands

  #resources :images TODO delete this and any other image artifacts
  resources :posts
  resources :categories, :only => [:index, :edit, :update]
  post "categories/:id/update", :to => "categories#update"
  get "post/create", :to => "posts#create"
  post "posts/:id/update", :to => "posts#update"

  root :to => "page#ember"

  #
  # Users
  #
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" } #, :skip => [:registrations,:passwords,:unlocks]
  # makes domain/login work as well as domain/users/login
  devise_scope :user do
    get "login"  => "devise/sessions#new"
    get "logout" => "devise/sessions#destroy"
    #delete "logout" => "devise/sessions#destroy"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    collection do
      get :whoami
      post :avatar
      post :validate_username
      get :validate_email
    end

    resources :followers, :only => [:index]
    resources :following, :only => [:index]
  end

  get "users/following/:id", :to => "users#following"

  get "users/username/:username", :to => "users#show", :identifier => "username"
  # Browser / system compatability
  post "users/:id/edit", :to => "users#update"
  post "users/:id/delete", :to => "users#destroy"

  #
  # Timelines
  #
  get "unseen", :to => "timelines#unseen" # test method for console, delete if you'd like
  get "timelines", :to => "timelines#index"
  get "timelines/users/:id", :to => "timelines#show_user"
  get "timelines/recent", :to => "timelines#show_recent"
  get "timelines/hashtags/:name", :to => "timelines#show_hashtags"

  #
  # Parser and Bookmarklet
  #
  get 'bookmarklet/iframe', :to => 'parser#iframe',      :as => :bookmarklet_iframe
  get 'bookmarklet',        :to => 'parser#bookmarklet', :as => :bookmarklet

  post "parse", :to => "parser#parse"
  get "dynascript", :to => "parser#dynascript"
  get "brandscript", :to => "parser#brandscript"


  #
  # Items
  #
  resources :items do
    member do
      get :image, :visit
      post :relift
    end
    get :search, :on => :collection
    resources :hashtags, :only => [:create]
  end
  # # Browser / system compatability
  post "items/:id/edit", :to => "items#update"
  post "items/:id/delete", :to => "items#destroy"

  get "createItem", :to => "items#create"
  get "history/:id", :to => "items#history"
  post "items/:id/email", :to => "items#email"

  #
  # Hashtags
  #
  get "hashtags/popular", :to => "hashtags#show_popular"
  get "hashtags/search", :to => "hashtags#search"
  delete "hashtags/:id" => "hashtags#destroy"
  post "hashtags/create", :to => "hashtags#create"
  # Browser / system compatability
  post "hashtags/:id/delete" => "hashtags#destroy"

  #
  # Subscriptions
  #
  get "subscriptions", :to => "subscriptions#index"
  get "subscriptions/users/:id", :to => "subscriptions#show"
  post "subscriptions", :to => "subscriptions#create"
  delete "subscriptions/:id", :to => "subscriptions#destroy"
  # Browser / system compatability
  post "subscriptions/users/:id/delete", :to => "subscriptions#destroy"

  #
  # Suggestions
  #
  get "suggestions", :to => "suggestions#index"

  #
  # Set Asides
  #
  get "set_asides", :to => "set_asides#index"
  post "set_asides", :to => "set_asides#create"
  delete "set_asides/items/:id", :to => "set_asides#destroy"
  # Browser / system compatability
  post "set_asides/items/:id/delete", :to => "set_asides#destroy"

  #
  # Flags
  #
  get "flags", :to => "flags#index"
  post "flags/items/:id", :to => "flags#create_item"
  post "flags/hashtags/:id", :to => "flags#create_hashtag"

  #
  # Statistics
  #
  get "statistics/users/:id", :to => "statistics#show_user"
  get "statistics/items/:id", :to => "statistics#show_item"

  #
  #Error Handling
  #
  match "/", :to => "application#render_error", :status => 404
  match "*path", :to => "application#render_error", :status => 404

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, :conditions => ["users.status = 1"], :counter_cache => :count_of_posts
  belongs_to :brand, :counter_cache => true
  has_many :hashtags, :conditions => ["hashtags.status = 1"]
  has_many :items, :conditions => ["items.status = 1"]
  has_many :post_flags, :conditions => ["post_flags.status = 1"]

  has_attached_file :photo,
                    :styles => {
                      :small => "383x383#"
                    },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :path => "/:style/:id/:filename"

  validates :url, :retailer, :user_id, :presence => true

  # todo turn this on after unit tests are modified
  #validates_attachment_presence :photo

  define_index do
    indexes name, :sortable => true
  end

end

app/controllers/posts_controller.rb
=begin apidoc
When a user clicks the bookmarklet while on a retailer page
posts_controller::create is invoked
create calls Parser::parse to get the brand, name, price, and description (and images, which are currenlty ignored)
note that the parsed value for brand is stored in a hidden parameter so the update action can determine
if the user modified the brand.
create then "creates" an initial post with initial values
create then renders json, html, or bookmarklet.js for user input

After the user has an opportunity to modify the brand, name, and price,
posts_controller::update is invoked
if the user modified the brand, name, or price
parser_audit::parse_audit is invoked to see if it can 'learn' by adding an xpath to the xpaths table
=end

class PostsController < ApplicationController
  include Parser
  include ParserAudit

  def new
    @post = current_user.posts.build
  end

  # =begin apidoc
  # url:: /post/create.json
  # method:: GET
  # access:: FREE
  # return:: create new post
  # param:: url:string - url
  # param:: retailer:string - retailer
  # param:: brand:string - brand
  # output:: json
  # {"brand_id":null,"comment":null,"created_at":"2012-06-28T14:59:46-05:00","description":"","hashtags_allowed":true,"id":224,"name":"Amazon.com: Zoolander Derek Zoolander School Heathered Royal Men's T-shirt: Clothing","photo_content_type":null,"photo_file_name":null,"photo_file_size":null,"photo_updated_at":null,"price":"18.73","relifts":0,"retailer":"www.amazon.com","status":1,"updated_at":"2012-06-28T14:59:46-05:00","url":"http://www.amazon.com/Zoolander-Derek-School-Heathered-T-shirt/dp/B006UI5KUG/ref=sr_1_3?ie=UTF8&qid=1340810439&sr=8-3&keywords=heathered men tshirt","user_id":11,"views":0,"visits":0}
  # ::output-end::
  # Create post
  # <br/><br/>Notes:<pre>curl -X GET --user dondenoncourt@gmail.com:vo2max localhost:3000/post/create.json?url=http%3A%2F%2Fwww.amazon.com%2FZoolander-Derek-School-Heathered-T-shirt%2Fdp%2FB006UI5KUG%2Fref%3Dsr_1_3%3Fie%3DUTF8%26qid%3D1340810439%26sr%3D8-3%26keywords%3Dheathered+men+tshirt</pre>
  # =end
  def create
    authenticate_user!
    params[:url] = "http://"+params[:retailer]+params[:url] if !params[:url].include? 'http:'
    post_params = parse(params[:url])
    @brand_name = post_params[:brand]
    post_params[:brand] = nil
    @images = post_params.delete(:images)
    @post = current_user.posts.create(post_params)
    respond_to do |format|
      format.html { render :edit }
      format.js { render :json => @post }
      format.json { render :json => @post }
    end
  end

  def edit
  end

  # =begin apidoc
  # url:: /post/:id/update.json
  # method:: POST
  # access:: FREE
  # return:: item object related to post
  # param:: id:int - post id
  # param:: post object (POST content)
  # output:: json
  # {"item":{"comment":null,"created_at":null,"id":null,"parent_id":null,"post_id":223,"relifts":0,"status":1,"updated_at":null,"user_id":12,"views":0,"visits":0}}
  # ::output-end::
  # Update post
  # <br/><br/>Notes:<pre>curl -X POST --user aaronbartell@gmail.com:poopydiaper -d "post[price]=12.35" localhost:3000/posts/223/update.json</pre>
  # =end
  def update
    @post = Post.find(params[:id])
    if params[:image]
      image = (params[:image].include? 'http:') ? params[:image] : ("http://"+params[:post][:retailer]+'/'+params[:image])
      Rails.logger.debug 'image:'+image
      @post.photo = open(image.gsub(/\s/, "%20"))
    end

    audit_params = Hash.new
    if params[:post][:brand] != params[:parser_brand]
      audit_params[:brand] = params[:post][:brand]
      audit_params[:name] = params[:post][:name]
    end
    if params[:post][:price] != params[:parser_price]
      audit_params[:price] = params[:post][:price]
    end

    if audit_params.length > 0
      audit_params[:url] = params[:post][:url]
      audit_params[:retailer] = params[:post][:retailer]
      audit_params[:parsed_name] = @post.name
      # TODO delay.parser_audit...
      parser_audit(audit_params)
    end

    @post.brand = Brand.find_or_create_by_name(params[:post][:brand])
    params[:post].delete(:brand)
    params[:post][:price] = params[:post][:price].gsub(/[^\d.]/, '') if params[:post][:price]

    if @post.update_attributes!(params[:post])
      @item = @post.items.create({ :user_id => current_user.id })
      if @item.persisted?
        #User.delay.share_lift(current_user.id, item_url(@item))
        respond_to do |format|
          format.html { redirect_to current_user }
          format.json { render :partial => 'items/item', :locals => {:item => @item}, :status => 201 }
        end
      else
        render :edit
      end
    else
      render :edit
    end
    Thread.new do
      User.share_lift(current_user.id, item_url(@item))
    end
    if params[:tags]
      # tags could be separated by spaces or commas - we don't know what the user might do
      hashtags = params[:tags].include?(',') ? params[:tags].split(',') : params[:tags].split(' ')
      hashtags.each do |hashtag_value|
        @hashtag_value = HashtagValue.where(:value => hashtag_value).first_or_create #.find_or_create_by_value(hashtag_value)
        if @hashtag_value.blank?
          # CONSIDER: post.errors[:base] << 'fails to create...' if entry_url.blank?
          return render_error(500,"Failed to create hashtag")
        end
        if !Hashtag.create({:user_id => current_user.id, :post_id => @item.post.id, :hashtag_value_id => @hashtag_value.id})
          return render_error(500,"Failed to create hashtag: "+hashtag_value+' '+@hashtag.errors[:hashtag_value_id][0])
        end
      end
    end
  end

end

app/views/posts/_post.html.erb
<div class="entry">
  <div class="entryHead">
    <%= link_to image_tag(post.user.avatar.url(:thumb)), '#' %>
    <p class="user">
      <%= link_to post.user.full_name, user_path(post.user) %>
      <br/><span class="location"><%= post.user.hometown %></span>
    </p>
  </div>
  <div class="productMain">
    <div class="product">
      <div class="productDetails">
        <h2><%= post.retailer %><br/><span class="productDescription"><%= post.name %></span></h2>
        <div class="price"><%= number_to_currency(post.price) %></div>
        <ul class="actions">
          <li><a href="#" class="modal" data-modalType="relift">Re-lift</a></li>
          <li><a href="#">Save</a></li>
          <li><a href="#" class="modal" data-modalType="share">Share</a></li>
          <li><a href="#">Buy</a></li>
        </ul>
      </div>
      <%= image_tag post.photo.url(:small) %>
    </div>
    <div class="productMeta">
      <div class="comment">
        <p><%= post.comment %></p>
        <p>Lifted <%= time_ago_in_words(post.created_at) %> Ago</p>
      </div>
      <ul class="tabs">
        <li class="current"><a href="#tagWrap">Tags</a></li>
        <li style="float:right"><a href="#historyWrap">History</a></li>
      </ul>
      <div class="toggleWrap" id="tagWrap" style="display:block;">
        <div class="add-tag">
          <form action="#">
            <img src="../img/global/user-thumb-holder.gif" alt="user-thumb-holder" width="25" height="25" class="user-tiny-thumb"/><input type="text" class="text" name="tag" value="Add a Tag" style="width:118px"/><input type="submit" name="submit" class="addSubmit" />
          </form>
        </div>
        <div class="itemList">
          <div class="scrollWrap">
            <ul>
              <% post.hashtags.each do |tag| %>
                <li><%= link_to user_image_and_value(tag.user, tag.hashtag_value.value), '#' %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="productTattle">
          <a href="#" class="modal flagItem" data-modalType="flagItem">Flag Item</a>
          <a href="#" class="modal reportTag" data-modalType="reportTag">Report a Tag</a>
        </div>
      </div>
      <div class="toggleWrap" id="historyWrap" style="display:none;">
        <% if post.items.any? %>
          <p>Re-Lifted By:</p>
          <div class="itemList">
            <div class="scrollWrap">
              <ul>
                <% post.items.each do |item| %>
                  <% next unless item.user.present? %>
                  <li><%= link_to user_image_and_value(item.user, item.user.full_name), '#' %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <p>First Lifted By:</p>
          <ul class="firstLifted">
            <li><%= link_to user_image_and_value(post.items.first.user, post.items.first.user.full_name), '#' %></li>
          </ul>
        <% else %>
          <p>No Re-lifts yet.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h2>Add An Item</h2>
<div class="modalContent">
  <%= form_for @post, :html => { :method => :put } do |f| %>

    <p>
      <%= f.label :brand %>
      <%= f.text_field :brand, :value => @brand_name %>
      <%= f.hidden_field :parser_brand, :value => @brand_name %>
    </p>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.hidden_field :parser_name, :value => @post.name %>
    </p>

    <p>
      <%= f.label :price %>
      <%= f.text_field :price %>
      <%= f.hidden_field :parser_price, :value => @post.price %>
    </p>

    <p>
      <%= f.label :description %>
      <%= f.text_area :description, :size => "5x5" %>
    </p>
    <p>
      <%= f.submit "Add", :class => 'submit' %>
    </p>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2>Add An Item</h2>
<div class="modalContent">
  <p>Install our Bookmarklet by dragging this button to your bookmarks bar:</p>
  <center>
    <%= link_to "Shoplift It", "javascript:(function(){var%20id='shoplift-bookmarklet-script',s=document.getElementById(id);if(s)s.parentNode.removeChild(s);s=document.createElement('script');s.setAttribute('src','#{bookmarklet_url(:format => :js)}?z='+(Math.random())+'&url='+escape(document.URL));s.setAttribute('type','text/javascript');s.setAttribute('id',id);document.body.appendChild(s);})();", :class => 'button' %>
    </center>

  <div class="divider">OR</div>

  <p>Add an Item from a url:</p>
  <%= form_for @post, :html => { :class => 'modal_form' } do |f| -%>
    <%= text_field_tag :url %>
    <%= f.submit "Add", :class => 'submit' %>
  <% end -%>
</div>