config/routes.rb
App::Application.routes.draw do

  get "page/emaildon", :to => "page#emaildon"

  get "page/home", :to => "page#home"
  get "page/ember", :to => "page#ember"
  get "/landing", :to => "page#landing"
  get "page/saved", :to => "page#saved"
  get "/terms_of_service", :to => 'page#terms_of_service'
  get "/buttons", :to => 'page#buttons'
  get "/privacy", :to => 'page#privacy'
  get "/contact", :to => 'page#contact'
  get "/about", :to => 'page#about'

  get "modal/report_tag", :to => "page#report_tag"
  get "modal/report_item", :to => "page#report_item"
  get "modal/relift", :to => "page#relift"
  get "modal/share", :to => "page#share"

  get 'hashtagbrands/search', :to => 'hashtagbrands#search'
  get 'hashtagbrands/:id/related', :to => 'hashtagbrands#related'
  resources :hashtagbrands

  #resources :images TODO delete this and any other image artifacts
  resources :posts
  resources :categories, :only => [:index, :edit, :update]
  post "categories/:id/update", :to => "categories#update"
  get "post/create", :to => "posts#create"
  post "posts/:id/update", :to => "posts#update"

  root :to => "page#ember"

  #
  # Users
  #
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" } #, :skip => [:registrations,:passwords,:unlocks]
  # makes domain/login work as well as domain/users/login
  devise_scope :user do
    get "login"  => "devise/sessions#new"
    get "logout" => "devise/sessions#destroy"
    #delete "logout" => "devise/sessions#destroy"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    collection do
      get :whoami
      post :avatar
      post :validate_username
      get :validate_email
    end

    resources :followers, :only => [:index]
    resources :following, :only => [:index]
  end

  get "users/following/:id", :to => "users#following"

  get "users/username/:username", :to => "users#show", :identifier => "username"
  # Browser / system compatability
  post "users/:id/edit", :to => "users#update"
  post "users/:id/delete", :to => "users#destroy"

  #
  # Timelines
  #
  get "unseen", :to => "timelines#unseen" # test method for console, delete if you'd like
  get "timelines", :to => "timelines#index"
  get "timelines/users/:id", :to => "timelines#show_user"
  get "timelines/recent", :to => "timelines#show_recent"
  get "timelines/hashtags/:name", :to => "timelines#show_hashtags"

  #
  # Parser and Bookmarklet
  #
  get 'bookmarklet/iframe', :to => 'parser#iframe',      :as => :bookmarklet_iframe
  get 'bookmarklet',        :to => 'parser#bookmarklet', :as => :bookmarklet

  post "parse", :to => "parser#parse"
  get "dynascript", :to => "parser#dynascript"
  get "brandscript", :to => "parser#brandscript"


  #
  # Items
  #
  resources :items do
    member do
      get :image, :visit
      post :relift
    end
    get :search, :on => :collection
    resources :hashtags, :only => [:create]
  end
  # # Browser / system compatability
  post "items/:id/edit", :to => "items#update"
  post "items/:id/delete", :to => "items#destroy"

  get "createItem", :to => "items#create"
  get "history/:id", :to => "items#history"
  post "items/:id/email", :to => "items#email"

  #
  # Hashtags
  #
  get "hashtags/popular", :to => "hashtags#show_popular"
  get "hashtags/search", :to => "hashtags#search"
  delete "hashtags/:id" => "hashtags#destroy"
  post "hashtags/create", :to => "hashtags#create"
  # Browser / system compatability
  post "hashtags/:id/delete" => "hashtags#destroy"

  #
  # Subscriptions
  #
  get "subscriptions", :to => "subscriptions#index"
  get "subscriptions/users/:id", :to => "subscriptions#show"
  post "subscriptions", :to => "subscriptions#create"
  delete "subscriptions/:id", :to => "subscriptions#destroy"
  # Browser / system compatability
  post "subscriptions/users/:id/delete", :to => "subscriptions#destroy"

  #
  # Suggestions
  #
  get "suggestions", :to => "suggestions#index"

  #
  # Set Asides
  #
  get "set_asides", :to => "set_asides#index"
  post "set_asides", :to => "set_asides#create"
  delete "set_asides/items/:id", :to => "set_asides#destroy"
  # Browser / system compatability
  post "set_asides/items/:id/delete", :to => "set_asides#destroy"

  #
  # Flags
  #
  get "flags", :to => "flags#index"
  post "flags/items/:id", :to => "flags#create_item"
  post "flags/hashtags/:id", :to => "flags#create_hashtag"

  #
  # Statistics
  #
  get "statistics/users/:id", :to => "statistics#show_user"
  get "statistics/items/:id", :to => "statistics#show_item"

  #
  #Error Handling
  #
  match "/", :to => "application#render_error", :status => 404
  match "*path", :to => "application#render_error", :status => 404

end

app/views/layouts/_footer.html.erb
<ul class="footer">
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Buttons", buttons_path %></li>
  <%#<li><a href="#">Mobile</a></li>%>
  <%#<li><a href="#">Blog</a></li>%>
  <li><%= link_to "Terms", terms_of_service_path %></li>
  <li><%= link_to "Privacy", privacy_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
</ul>
<%= link_to "Scroll to Top", '#', :class => 'scrollTo', :style => 'display:none;' %>

app/views/layouts/_header.html.erb
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# the_shoplift: http://ogp.me/ns/fb/the_shoplift#">
	<meta charset="utf-8">
	<title>The Shoplift: <%= full_title(yield(:title)) %></title>
	
	<meta name="description" content="The Shoplift" />
	<meta name="keywords" content="The Shoplift" />	
	<meta name="author" content="The Shoplift" />
  <%= yield :head %>
  
  <!-- note: if you use any stylesheet other than the application.css manifest, it becomes manual --> 
  <%= stylesheet_link_tag "style"	%>
  <%= stylesheet_link_tag "webfonts/stylesheet"%>	
  <%= stylesheet_link_tag "main"	%>
  <%= stylesheet_link_tag "page"	%>

  <%= javascript_include_tag "shared/shared" %>
</head>

app/views/layouts/_subhead.html.erb
<div class="header">
  <div class="logoPan">
      <%= link_to image_tag("shop-lift-logo.png", width:"414px", height:"102px"), '/' %></a>
  </div>
    <% if user_signed_in? %>
      <div class="profilePan">
          <div class="profilePan-img-ring"></div><!--/profilePan-img-ring-->
            <div class="profilePan-img-circle-overflow">
              <%= image_tag(current_user.avatar.url(:small), height: '65', width: '65') %>
            </div>
            <ul id="mainMenu">
              <li><%= link_to "Add", new_post_path, :class => 'modal_link' %></li>
              <li><%= link_to "Follow", users_path %> </li>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Saved", user_path(current_user, :saved => true) %></li>
              <li><%= link_to_function "Search", "alert('Not yet!')" %></li>
              <li class="arrowLink"><a href="#" class="arrow">></a>
                <ul>
                  <li><%= link_to_function "Invite", "alert('Not yet!')" %></li>
                  <li><%= link_to_function "Help", "alert('Not yet!')" %></li>
                  <li><%= link_to "Buttons", buttons_path %></li>
                  <li><a href="#" title="About">About</a></li>
                  <li><%= link_to_function "Blog", "alert('Not yet!')" %></li>
                  <li><a href="/logout" title="Sign Out">Sign Out</a></li>
                </ul>
              </li>
            </ul>
          </div>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render "layouts/header" %>
<body>
  <% if params[:action] != 'home' %>
  
    <%= render "layouts/subhead" %>
    <div id="content">
    <% flash.each do |name, msg| %>
      <div class="rightCol">
        <%= content_tag :div, msg.html_safe, :id => "flash_#{name}", :class => 'entry' %>
      </div>
    <% end %>
    <%= yield :layout %>
    </div>
    <%= render "layouts/footer" %>
    <div id="basic-modal-content"></div>
    <script type="text/javascript" src="http://s.skimresources.com/js/37030X960874.skimlinks.js"></script>
    
  <% else %>
    <%= yield :layout %>
  <% end %>  
</body>
</html>

app/views/layouts/horizontal.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# the_shoplift: http://ogp.me/ns/fb/the_shoplift#">
	<meta charset="utf-8">
	<title>The Shoplift</title>
	<meta name="description" content="The Shoplift" />
	<meta name="keywords" content="The Shoplift" />	
	<meta name="author" content="The Shoplift" />
  <%= yield :head %>
  <!-- note: if you use any stylesheet other than the application.css manifest, it becomes manual --> 
  <%= stylesheet_link_tag "style"	%>
  <%= stylesheet_link_tag "relift-popup-styles" %>
  <%= stylesheet_link_tag "webfonts/stylesheet"%>	
  <%= stylesheet_link_tag "share-popup-styles"	%>
  <!-- note: main.css and page.css that are in _header.html.erb cause issues --> 
  <%= javascript_include_tag "application" %>
</head>
<body>

  <%= render "layouts/subhead" %>

<% flash.each do |name, msg| %>
  <div class="rightCol">
    <%= content_tag :div, msg.html_safe, :id => "flash_#{name}", :class => 'entry' %>
  </div>
<% end %>
<%= yield :layout %>
  <div id="basic-modal-content"></div>
<script type="text/javascript" src="http://s.skimresources.com/js/37030X960874.skimlinks.js"></script>    
<script type="text/javascript" src="//use.typekit.net/sli7ixm.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</body>
</html>

app/views/layouts/iframe.html.erb
<!DOCTYPE html>
<html>
  <head>
  <style>
    /* http://meyerweb.com/eric/tools/css/reset/
       v2.0 | 20110126
       License: none (public domain)
    */

    html, body, div, span, applet, object, iframe,
    h1, h2, h3, h4, h5, h6, p, blockquote, pre,
    a, abbr, acronym, address, big, cite, code,
    del, dfn, em, img, ins, kbd, q, s, samp,
    small, strike, strong, sub, sup, tt, var,
    b, u, i, center,
    dl, dt, dd, ol, ul, li,
    fieldset, form, label, legend,
    table, caption, tbody, tfoot, thead, tr, th, td,
    article, aside, canvas, details, embed,
    figure, figcaption, footer, header, hgroup,
    menu, nav, output, ruby, section, summary,
    time, mark, audio, video {
      margin: 0;
      padding: 0;
      border: 0;
      font-size: 100%;
      font: inherit;
      vertical-align: baseline;
    }
    /* HTML5 display-role reset for older browsers */
    article, aside, details, figcaption, figure,
    footer, header, hgroup, menu, nav, section {
      display: block;
    }
    body {
      line-height: 1;
    }
    ol, ul {
      list-style: none;
    }
    blockquote, q {
      quotes: none;
    }
    blockquote:before, blockquote:after,
    q:before, q:after {
      content: '';
      content: none;
    }
    table {
      border-collapse: collapse;
      border-spacing: 0;
    }

    .clear {
     clear:both;
    }
    #sl-bookmarklet-main {
      position : fixed;
      width : 100%;
      height : 100%;
      z-index : 2147483647;
      top : 0;
      left : 0;
      cursor : pointer;
    }
    #sl-bookmarklet-background {
      position : absolute;
      width : 100%;
      height : 100%;
      background : #19032f; /* purple */
      top : 0;
      left : 0;
      opacity:.8;
    }
    #sl-booklet-error {
     position: absolute;
      color : #EFFFB0; /* yellow */
      text-align: center;
     font-family: "futura", arial;
      font-size: 26px;
      font-weight: bold;
      font-style: italic;
      top: 179px;
      left: 86px;
      height: 40px;
      display:none;
    }
    .tsl-booklet-wrap {
     background:url(/assets/tsl-booklet-vert-scaffolding.png) center repeat-y;
     width:100%;
     height:100%;
     padding-top:0px;
    }
    .tsl-booklet-one {
     width:439px;
     height: 512px;
     margin:0 auto 0;
     position:relative;
      opacity:.9;
      background-image: url(/img/bookmarklet-scaffolding.png);
    }
    .tsl-booklet-two {
     width:439px;
     height: 631px;
     margin:0 auto 0;
     position:relative;
     opacity:.9;
     background-image: url(/img/bookmarklet-scaffolding-2.png);
    }
    .tsl-booklet-header-logo {
     width:439px;
     height:235px;
    }
    .close {
     background:url(/assets/tsl-booklet-close-btn.png) no-repeat;
     width:41px;
     height:42px;
     display:block;
     position:absolute;
     top: 24px;
     right: -18px;
    }
    .tsl-booklet-scaffold {
     width:449px;
     height:300px;
     margin-top:-17px;
     position:relative;
    }

    .tsl-booklet-second-screen-scaffold .tsl-booklet-right-content {
     width:218px;
     height:294px;
    }
    .tsl-booklet-img-shadow {
     width:180px;
     height:192px;
     position:absolute;
     top: 24px;
     left: 13px;
     z-index:0;
    }
    .tsl-booklet-img {
     width:180px;
     height:192px;
     z-index:-445;
     position:absolute;
    }
    .tsl-booklet-img-text-box {
     background:url(/assets/tsl-booklet-img-text-box.png) no-repeat;
     width:214px;
     height:50px;
     position:absolute;
     bottom:0px;
     left:5px;
     overflow:hidden;
     padding:1px 13px 0;
     display:none;
     text-shadow: 1px 1px 1px #000;
     filter: dropshadow(color=#000, offx=1, offy=1);
    }
    .tsl-booklet-brand-text {
     font-family: "futura", arial;
     font-size:18px !important;
     color:#f8ece5 !important;
     height:18px;
     padding-bottom:4px;
     text-wrap:none;
    }
    .tsl-booklet-item-text {
     font-family: "futura", arial;
     font-size:14px !important;
     color:#f8ece5 !important;
     height:18px;
     text-wrap:none;
     float:left;
     min-width:20px;
    }
    .tsl-booklet-price-text {
     font-family: "futura", arial;
     font-size:14px !important;
     color:#d6fc56 !important;
     height:148px;
     text-wrap:none;
     float:left;
     min-width:20px;
     padding-left:3px;
    }
    .tsl-booklet-one .tsl-booklet-right-content {
     width: 207px;
     height: 266px;
     background-image: url(/img/bookmarklet-right-bg.png);
     background-repeat: no-repeat;
     position: absolute;
     top: 5px;
     padding-top: 16px;
     right: 21px;
    }
    .tsl-booklet-form {
     width:207px;
     padding-top:3px;
    }
    .tsl-booklet-two .tsl-booklet-first-screen-form {
     display: none;
    }
    .tsl-booklet-form input {
     width:205px;
     height:30px;
     font-family: "futura", arial;
     font-size:15px !important;
     color:#18022e !important;
     padding:0;
     margin-bottom: 25px;
    }
    .tsl-booklet-first-screen-form textarea {
     width:191px;
     height:69px;
     font-family: "futura", arial;
     font-size:15px !important;
     color:#18022e !important;
     padding:0;
     margin-bottom: 28px;
    }
    .blank-input {
     background-color:#FF99A4;
    }
    .tsl-booklet-input-brand {
     margin-bottom:10px
    }
    .tsl-booklet-input-item {
     margin-bottom:7px
    }
    .tsl-booklet-input-price {
     margin-bottom:7px
    }

    .tsl-booklet-form h4 {
     font-family: "futura", arial;
     font-size:14px !important;
     padding-bottom:1px;
      margin-top:1px;
      margin-bottom:1px;
     color:#ffece6 !important;
    }
    .tsl-booklet-next-btn {
     display:block;
     height: 17px;
     position: absolute;
    }
    .tsl-booklet-back-btn {
     background:url(/img/bookmarklet-cancel.png) left center no-repeat;
     width: 93px;
     height: 17px;
     position: absolute;
    }

    .tsl-booklet-one .tsl-booklet-next-btn {
     background:url(/img/bookmarklet-continue.png) right center no-repeat;
     margin-right: -6px;
     width: 119px;
     bottom: 29px;
     right: 0px;
    }
    .tsl-booklet-one .tsl-booklet-back-btn {
     bottom: -1px;
     right: -7px;
    }

    .tsl-booklet-two .tsl-booklet-next-btn {
     background:url(/img/bookmarklet-shoplift-now.png) right center no-repeat;
     margin-right: -6px;
     width: 175px;
     bottom: 36px;
     right: 0px;
    }
    .tsl-booklet-two .tsl-booklet-back-btn {
     bottom: 5px;
     right: -7px;
    }
    .tsl-booklet-two .tsl-booklet-right-content {
     width: 207px;
     height: 394px;
     background-repeat: no-repeat;
     position: absolute;
     top: 5px;
     padding-top: 16px;
     right: 21px;
    }
    .tsl-booklet-second-screen-form {
     padding-top:7px;
     display: block;
    }
    .tsl-booklet-one .tsl-booklet-second-screen-form {
     display:none;
    }
    .tsl-booklet-second-screen-formgh4 {
     padding-bottom:5px;
    }
    .tsl-booklet-first-screen-form textarea{
     font-family: "futura", arial;
     font-size:15px !important;
     color:#18022e !important;
      background-color: white;
     padding:0 8px;
    }
    .tsl-booklet-textarea-tags {
     width: 154px;
     height: 186px;
     left: 49px;
     top: 19px;
     position: absolute;
    }
    .tsl-booklet-input-thoughts {
     position: absolute;
     top: 242px;
     left: -163px;
     width: 366px;
     height: 87px;
    }
    .booklet-submit {
     background:url(/assets/booklet-submit-btn.png) left center no-repeat;
      border-style: none;
     width:116px !important;
     height:46px !important;
     margin:0px !important;
     padding:0px !important;
     position:absolute;
     bottom: -9px;
     right: -4px;
     display:none;
    }

    @-webkit-keyframes reset {
      0%   { opacity: 0; }
      100% { opacity: 0; }
    }

    @-webkit-keyframes fade-in {
      0%    { opacity: 0; }
      100%  { opacity: 1; }
    }

    @-webkit-keyframes fade-in-late {
      0%    { opacity: 0; }
      90%   { opacity: 0; }
      100%  { opacity: 1; }
    }
    .fade-in {
      -webkit-animation-name: reset, fade-in;
         -moz-animation-name: reset, fade-in;
          -ms-animation-name: reset, fade-in;
           -o-animation-name: reset, fade-in;
              animation-name: reset, fade-in;

      -webkit-animation-duration: 0.5s;
         -moz-animation-duration: 0.5s;
          -ms-animation-duration: 0.5s;
           -o-animation-duration: 0.5s;
              animation-duration: 0.5s;

      -webkit-animation-timing-function: ease-in;
         -moz-animation-timing-function: ease-in;
          -ms-animation-timing-function: ease-in;
           -o-animation-timing-function: ease-in;
              animation-timing-function: ease-in;

      -webkit-animation-iteration-count: 1;
         -moz-animation-iteration-count: 1;
          -ms-animation-iteration-count: 1;
           -o-animation-iteration-count: 1;
    }

  </style>
  </head>
  <body class="fade-in">
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render "page/header" %>
<body>
  <%= render "page/subhead" %>
  <div id="content">
    <%= yield :layout %>
  </div>
  <%= render "page/footer" %>
</body>
</html>